// Generated by Rcpp::compileAttributes() - do not edit by hand
// Please edit the file(s) included below instead

#include <Rcpp.h>

using namespace Rcpp;

#ifdef __cplusplus
extern "C" {
#endif

// Placeholder for Rcpp registration
// Actual registration code will be auto-generated by Rcpp::compileAttributes()

#ifdef __cplusplus
}
#endif
