// Generated by Rcpp::compileAttributes() — edits will be overwritten
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pruning_llik_cpp
double pruning_llik_cpp(IntegerVector parent_vec, IntegerVector child_vec, NumericVector edge_lengths, IntegerVector tip_states, NumericMatrix Q_mat, NumericVector rates, NumericVector root_prior, int ntip, int nnode);
RcppExport SEXP _RateScape_pruning_llik_cpp(SEXP parent_vecSEXP, SEXP child_vecSEXP, SEXP edge_lengthsSEXP, SEXP tip_statesSEXP, SEXP Q_matSEXP, SEXP ratesSEXP, SEXP root_priorSEXP, SEXP ntipSEXP, SEXP nnodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec(parent_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_vec(child_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_lengths(edge_lengthsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q_mat(Q_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rates(ratesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type root_prior(root_priorSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< int >::type nnode(nnodeSEXP);
    rcpp_result_gen = Rcpp::wrap(pruning_llik_cpp(parent_vec, child_vec, edge_lengths, tip_states, Q_mat, rates, root_prior, ntip, nnode));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_sweep_cpp
List gibbs_sweep_cpp(IntegerVector parent_vec, IntegerVector child_vec, NumericVector edge_lengths, IntegerVector tip_states, NumericMatrix Q_mat, NumericVector rates, IntegerVector z_indicators, double pi_val, double sigma2, NumericVector root_prior, int ntip, int nnode, double rate_proposal_sd);
RcppExport SEXP _RateScape_gibbs_sweep_cpp(SEXP parent_vecSEXP, SEXP child_vecSEXP, SEXP edge_lengthsSEXP, SEXP tip_statesSEXP, SEXP Q_matSEXP, SEXP ratesSEXP, SEXP z_indicatorsSEXP, SEXP pi_valSEXP, SEXP sigma2SEXP, SEXP root_priorSEXP, SEXP ntipSEXP, SEXP nnodeSEXP, SEXP rate_proposal_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec(parent_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_vec(child_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_lengths(edge_lengthsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q_mat(Q_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rates(ratesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z_indicators(z_indicatorsSEXP);
    Rcpp::traits::input_parameter< double >::type pi_val(pi_valSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type root_prior(root_priorSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< int >::type nnode(nnodeSEXP);
    Rcpp::traits::input_parameter< double >::type rate_proposal_sd(rate_proposal_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sweep_cpp(parent_vec, child_vec, edge_lengths, tip_states, Q_mat, rates, z_indicators, pi_val, sigma2, root_prior, ntip, nnode, rate_proposal_sd));
    return rcpp_result_gen;
END_RCPP
}
// batch_branch_llik_cpp
NumericMatrix batch_branch_llik_cpp(IntegerVector parent_vec, IntegerVector child_vec, NumericVector edge_lengths, IntegerVector tip_states, NumericMatrix Q_mat, NumericVector base_rates, NumericVector rate_categories, NumericVector root_prior, int ntip, int nnode);
RcppExport SEXP _RateScape_batch_branch_llik_cpp(SEXP parent_vecSEXP, SEXP child_vecSEXP, SEXP edge_lengthsSEXP, SEXP tip_statesSEXP, SEXP Q_matSEXP, SEXP base_ratesSEXP, SEXP rate_categoriesSEXP, SEXP root_priorSEXP, SEXP ntipSEXP, SEXP nnodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type parent_vec(parent_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_vec(child_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type edge_lengths(edge_lengthsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type tip_states(tip_statesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Q_mat(Q_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type base_rates(base_ratesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate_categories(rate_categoriesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type root_prior(root_priorSEXP);
    Rcpp::traits::input_parameter< int >::type ntip(ntipSEXP);
    Rcpp::traits::input_parameter< int >::type nnode(nnodeSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_branch_llik_cpp(parent_vec, child_vec, edge_lengths, tip_states, Q_mat, base_rates, rate_categories, root_prior, ntip, nnode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RateScape_pruning_llik_cpp", (DL_FUNC) &_RateScape_pruning_llik_cpp, 9},
    {"_RateScape_gibbs_sweep_cpp", (DL_FUNC) &_RateScape_gibbs_sweep_cpp, 13},
    {"_RateScape_batch_branch_llik_cpp", (DL_FUNC) &_RateScape_batch_branch_llik_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_RateScape(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
