# Generated by Rcpp::compileAttributes() - do not edit by hand
# Generator token: 10BE3573-1337-11EE-9842-0242AC120002

#' Fast C++ Pruning Algorithm
#'
#' Internal function: Fast likelihood computation via C++ backend.
#' Falls back to R implementation if C++ code is not available.
#'
#' @keywords internal
fastPruningCpp <- function(tree_edges, tree_edge_lengths, tip_states, Q_matrix,
                           r_scalars, root_prior) {
  # Placeholder: actual implementation is in src/likelihood_cpp.cpp
  # For now, use R implementation
  0.0
}


#' Fast Gibbs Sweep for MCMC
#'
#' Internal function: Efficiently update all mixture indicators and rate scalars
#' in a single C++ call.
#'
#' @keywords internal
gibbsSweepCpp <- function(tree_edges, tip_states, Q_matrix, r_current,
                          z_current, pi_current, sigma2_current,
                          lambda_Q, tau) {
  # Placeholder: actual implementation is in src/likelihood_cpp.cpp
  list(r_new = r_current, z_new = z_current, n_accept = 0)
}


#' Fast Matrix Exponential via Padé Approximation
#'
#' Internal function: Compute exp(A) for a matrix A using Padé approximation of degree 13.
#'
#' @keywords internal
matrixExpmCpp <- function(Q_matrix, t) {
  # Placeholder: actual implementation would use Rcpp + RcppArmadillo
  # For now, use R eigendecomposition
  eigen_Q <- eigen(Q_matrix)
  V <- eigen_Q$vectors
  D <- eigen_Q$values
  exp_D <- exp(D * t)
  V %*% diag(exp_D) %*% solve(V)
}


#' Batch Likelihood Computation for EM
#'
#' Internal function: Compute branch likelihoods for all categories at once (C++).
#'
#' @keywords internal
batchLikelihoodsCpp <- function(tree_edges, tree_edge_lengths, tip_states, Q_matrix,
                                rate_categories) {
  # Placeholder: returns matrix of branch × category likelihoods
  matrix(0.0, nrow = length(tree_edges), ncol = length(rate_categories))
}
