# Generated by Rcpp::compileAttributes() — edits will be overwritten
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RateScape, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

pruning_llik_cpp <- function(parent_vec, child_vec, edge_lengths,
                              tip_states, Q_mat, rates, root_prior,
                              ntip, nnode) {
  .Call(`_RateScape_pruning_llik_cpp`, parent_vec, child_vec, edge_lengths,
        tip_states, Q_mat, rates, root_prior, ntip, nnode)
}

gibbs_sweep_cpp <- function(parent_vec, child_vec, edge_lengths,
                             tip_states, Q_mat, rates, z_indicators,
                             pi_val, sigma2, root_prior, ntip, nnode,
                             rate_proposal_sd) {
  .Call(`_RateScape_gibbs_sweep_cpp`, parent_vec, child_vec, edge_lengths,
        tip_states, Q_mat, rates, z_indicators, pi_val, sigma2,
        root_prior, ntip, nnode, rate_proposal_sd)
}

batch_branch_llik_cpp <- function(parent_vec, child_vec, edge_lengths,
                                   tip_states, Q_mat, base_rates,
                                   rate_categories, root_prior,
                                   ntip, nnode) {
  .Call(`_RateScape_batch_branch_llik_cpp`, parent_vec, child_vec,
        edge_lengths, tip_states, Q_mat, base_rates, rate_categories,
        root_prior, ntip, nnode)
}
